import { ref } from "vue";

// The shipped sky dataset (frontend/src/assets/skymap.json), generated by `just gen-skymap-data`.
// Positions are J2000 equatorial degrees; `lines`/`names` index into `stars`.
export interface SkyMapData {
  magLimit: number;
  source: string;
  stars: [number, number, number][]; // [raDeg, decDeg, mag]
  names: [number, string][]; // [starIndex, properName]
  lines: [number, number][]; // constellation figure segments (star index pairs)
  constellations: { name: string; ra: number; dec: number }[];
}

// Loaded once and shared process-wide: the dataset is a static bundled asset, imported as a lazy chunk
// only when the sky map first mounts (never in the app shell).
let cache: SkyMapData | null = null;
let inflight: Promise<SkyMapData> | null = null;

export function useSkyCatalog() {
  const data = ref<SkyMapData | null>(cache);
  const loading = ref(false);

  async function load(): Promise<SkyMapData> {
    if (cache) {
      data.value = cache;
      return cache;
    }
    if (!inflight) {
      loading.value = true;
      inflight = import("@/assets/skymap.json")
        .then((m) => {
          cache = m.default as unknown as SkyMapData;
          return cache;
        })
        .finally(() => {
          loading.value = false;
        });
    }
    const d = await inflight;
    data.value = d;
    return d;
  }

  return { data, loading, load };
}
